### ISSUE TITLE
When "Draw" is applied on an existing photo the size changes

### ISSUE THREAD

**Issue by rhisss** [beck24/draw#3]
When "Draw" is applied on an existing photo (jpeg, jpg etc ) the size changes - the height is reduced.
If the jpeg is smaller than the "Draw" canvas, the height-width of the resultant image increases than the original image. However this is a very minor bug - probably needs no fix.

**Comment by beck24** [comment]
Yeah there's nothing I can really do about that, it's limited to the size of the canvas so large existing images are scaled down to fit.  Also the image data is encoded for the form submit so is larger than the file upload would be and needs to ideally not trigger any php data size limits.

**Comment by rhisss** [comment]
Can the canvas size be increased ?
The problem is not just the size, the height:width ratio is altered, it seems to add a "white border" on top and bottom of the image. The thumbnails are also distorted/misaligned with rest of the thumbnails after editing/drawing on an existing image.

**Comment by beck24** [comment]
Yeah the size is determined by the size of the container div, so it can be changed simply by overriding the css.  What do you mean about the thumbnails?
You are correct, it's "editing" the image per se, it's creating a brand new image that is you drawing over a background of the original image.  Therefore the properties of the file are 'altered' because it's not the same file.

**Comment by rhisss** [comment]
I am not finding the css under views. Is it elsewhere? The thumbnails are same size as before but white space is added on both sides within the same width, so the display of an edited image's thumbnail looks odd in comparison to the other thumbnails.
![untitled](https://cloud.githubusercontent.com/assets/3778500/5515079/ccc38e8e-887f-11e4-984b-3abbd5069208.PNG)
